/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PsSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface PsStockFinder {
    }
    interface PsStockPrice {
        "stockSymbol": string;
    }
    interface PsTooltip {
        "text": string;
    }
}
declare global {
    interface HTMLPsSideDrawerElement extends Components.PsSideDrawer, HTMLStencilElement {
    }
    var HTMLPsSideDrawerElement: {
        prototype: HTMLPsSideDrawerElement;
        new (): HTMLPsSideDrawerElement;
    };
    interface HTMLPsStockFinderElement extends Components.PsStockFinder, HTMLStencilElement {
    }
    var HTMLPsStockFinderElement: {
        prototype: HTMLPsStockFinderElement;
        new (): HTMLPsStockFinderElement;
    };
    interface HTMLPsStockPriceElement extends Components.PsStockPrice, HTMLStencilElement {
    }
    var HTMLPsStockPriceElement: {
        prototype: HTMLPsStockPriceElement;
        new (): HTMLPsStockPriceElement;
    };
    interface HTMLPsTooltipElement extends Components.PsTooltip, HTMLStencilElement {
    }
    var HTMLPsTooltipElement: {
        prototype: HTMLPsTooltipElement;
        new (): HTMLPsTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "ps-side-drawer": HTMLPsSideDrawerElement;
        "ps-stock-finder": HTMLPsStockFinderElement;
        "ps-stock-price": HTMLPsStockPriceElement;
        "ps-tooltip": HTMLPsTooltipElement;
    }
}
declare namespace LocalJSX {
    interface PsSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface PsStockFinder {
        "onPsSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface PsStockPrice {
        "stockSymbol"?: string;
    }
    interface PsTooltip {
        "text"?: string;
    }
    interface IntrinsicElements {
        "ps-side-drawer": PsSideDrawer;
        "ps-stock-finder": PsStockFinder;
        "ps-stock-price": PsStockPrice;
        "ps-tooltip": PsTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ps-side-drawer": LocalJSX.PsSideDrawer & JSXBase.HTMLAttributes<HTMLPsSideDrawerElement>;
            "ps-stock-finder": LocalJSX.PsStockFinder & JSXBase.HTMLAttributes<HTMLPsStockFinderElement>;
            "ps-stock-price": LocalJSX.PsStockPrice & JSXBase.HTMLAttributes<HTMLPsStockPriceElement>;
            "ps-tooltip": LocalJSX.PsTooltip & JSXBase.HTMLAttributes<HTMLPsTooltipElement>;
        }
    }
}
